name: CI - Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          442042528689.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t checkinmty-web .

      - name: Tag image
        run: |
          docker tag checkinmty-web:latest 442042528689.dkr.ecr.us-east-2.amazonaws.com/checkinmty-web:latest

      - name: Push image to ECR
        run: |
          docker push 442042528689.dkr.ecr.us-east-2.amazonaws.com/checkinmty-web:latest
